Lab6
nastusya/MobLaba pull request #6
Opened 2018-10-29 11:31 UTC by nastusya

2018-11-01 08:42 UTC, ovovchak requested changes

2018-11-01 08:42 UTC, ovovchak commented on app/src/main/java/com/example/nastya/laba/http_client/ApiClientInstance.java
> +    private static Retrofit retrofit;
забрати статік

2018-11-01 08:42 UTC, ovovchak commented on app/src/main/java/com/example/nastya/laba/http_client/ApiClientInstance.java
> +                    .addConverterFactory(GsonConverterFactory.create())
забрати цей іф, зробити метод не статичним

2018-11-01 08:42 UTC, ovovchak commented on app/src/main/java/com/example/nastya/laba/http_client/ApiClientInstance.java
> +    public static RedditApi getApiService() {
він не мав би бути статичним

2018-11-01 08:42 UTC, ovovchak commented on app/build.gradle
>      implementation fileTree(dir: 'libs', include: ['*.jar'])
-

2018-11-01 08:42 UTC, ovovchak commented on app/src/main/AndroidManifest.xml
> +        android:name=".http_client.ApiClientInstance"
винести

2018-11-01 08:42 UTC, ovovchak commented on app/src/main/java/com/example/nastya/laba/activities/MainActivity.java
> +    RecyclerView recyclerView;
protected

2018-11-01 08:42 UTC, ovovchak commented on app/src/main/java/com/example/nastya/laba/activities/MainActivity.java
> +    public static RedditAdapter adapter;
static

2018-11-01 08:42 UTC, ovovchak commented on app/src/main/java/com/example/nastya/laba/activities/MainActivity.java
> +        makeCall();
забрати

2018-11-01 08:42 UTC, ovovchak commented on app/src/main/java/com/example/nastya/laba/activities/MainActivity.java
> +        call.clone().enqueue(new Callback <Feed>() {
для чого тут clone()

2018-11-01 08:42 UTC, ovovchak commented on app/src/main/java/com/example/nastya/laba/activities/MainActivity.java
> +        adapter = new RedditAdapter(data);
адаптер треба створювати раз на онкріейт

 public void update(final List<Movie> movies) {
        this.movies.clear();
        this.movies.addAll(movies);

        this.notifyDataSetChanged();
    }

2018-11-01 08:42 UTC, ovovchak commented on app/src/main/java/com/example/nastya/laba/activities/MainActivity.java
> +        makeCall();
дані завжди вантажать на onResume

2018-11-01 08:42 UTC, ovovchak commented on app/src/main/java/com/example/nastya/laba/adapters/RedditViewHolder.java
> +    TextView title;
модифікатори

2018-11-08 08:40 UTC, MarkoKuspis approved these changes

2018-11-08 08:40 UTC, MarkoKuspis commented on app/src/main/java/com/example/nastya/laba/activities/MainActivity.java
> +    public RedditAdapter adapter;
No reason for this to be public

2018-11-08 08:40 UTC, MarkoKuspis commented on app/src/main/java/com/example/nastya/laba/activities/MainActivity.java
> +        recyclerView.setAdapter(adapter);
You should not create adapter and layout manager every time items are loaded. They should be created once, on screen start. Than you should add items to adapter once they are loaded

2018-11-20 20:41 UTC, merged